# Generated by Django 4.1.2 on 2022-10-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
