# Generated by Django 4.1.2 on 2022-10-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ad_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={},
        ),
    ]
