# Generated by Django 4.1.2 on 2022-10-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ad_options_alter_rubric_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.rubric'),
        ),
    ]
